apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-nodejs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-nodejs
    spec:
      containers:
      - name: kubernetes-nodejs
        image: kubernetes-nodejs:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080