apiVersion: v1
kind: Service
metadata:
  name: kubernetes-nodejs
  labels:
    app: kubernetes-nodejs
spec:
  selector:
    app: kubernetes-nodejs
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30001
  type: LoadBalancer